apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-source
  labels:
    type: "local"
spec:
  storageClassName: ""
  capacity:
    storage: "8Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/extstorage/authentik/postgresql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - espresso-2