apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: authentik
  name: postgresql-source
spec:
  storageClassName: longhorn-hard-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "8Gi"
  volumeName: postgresql-source