apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: synology-csi-chart
    repo: https://christian-schlichtherle.github.io/synology-csi-chart
    version: 0.9.8
    releaseName: synology-csi
    namespace: synology-csi
    valuesFile: values.yaml

namespace: synology-csi
