apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-prd
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: josephangbc@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    # Enable the HTTP-01 challenge provider
    solvers:
      - selector:
          dnsZones:
          - kopi.quest
        dns01:
          cloudflare:
            email: josephangbc@gmail.com
            apiTokenSecretRef:
              name: cloudflare-apikey-secret
              key: apikey
