apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.7.1
      path: ingress-nginx 
      chart: ingress-nginx 
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $valuesFilesRepo/.helm/ingress-nginx/values.yaml
    - repoURL: https://github.com/JosephABC/argocd.git
      ref: valuesFilesRepo
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
