apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/JosephABC/argocd.git
    targetRevision: HEAD
    path: .kustomize/metallb
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true