apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: 2.17.0
      path: pihole-kubernetes
      chart: pihole
      helm:
        releaseName: pi-hole
        valueFiles:
          - $valuesFilesRepo/.helm/values.yaml
    - repoURL: https://github.com/JosephABC/argocd.git
      ref: valuesFilesRepo
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated: {}
