apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.17.0
    path: pihole-kubernetes
    chart: pi-hole
    helm:
      releaseName: pi-hole
      valueFiles:
      - ../../.helm/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated: {}
