apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: authentik
  name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: synology-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Gi"
