apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: authentik
  name: postgresql
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "8Gi"
  volumeName: postgresql