apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: authentik
  name: postgresql
spec:
  storageClassName: longhorn-sd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "8Gi"
