apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/metallb/metallb/config/native?ref=v0.13.10
  - resources/ip_address_pool.yaml
  - resources/l2_advertisement.yaml

namespace: metallb-system