apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.7/manifests/install.yaml
  - resources/argocd-app.yaml
  - resources/argocd-projects-app.yaml
  - resources/ingress.yaml

patches:
  - path: patches/argocd-cmd-params-cm.yaml
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-rbac-cm.yaml

namespace: argocd