apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/main/cmd/k8s-operator/manifests/operator.yaml
  - secrets/client-secret.yaml

patches:
  - path: patches/remove-secret.yaml
  - path: patches/deployment.yaml

namespace: tailscale