auth:
  database: authentik
  username: authentik
  existingSecret: postgresql

primary:
  persistence:
    existingClaim: postgresql
  resources:
    requests:
      memory: 500Mi

volumePermissions:
  enabled: true
