apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Prometheus Operator
  - https://github.com/prometheus-operator/kube-prometheus/blob/release-0.13/manifests/prometheusOperator-clusterRole.yaml
  - https://github.com/prometheus-operator/kube-prometheus/blob/release-0.13/manifests/prometheusOperator-clusterRoleBinding.yaml
  - https://github.com/prometheus-operator/kube-prometheus/blob/release-0.13/manifests/prometheusOperator-deployment.yaml
  - https://github.com/prometheus-operator/kube-prometheus/blob/release-0.13/manifests/prometheusOperator-networkPolicy.yaml
  - https://github.com/prometheus-operator/kube-prometheus/blob/release-0.13/manifests/prometheusOperator-prometheusRule.yaml
  - https://github.com/prometheus-operator/kube-prometheus/blob/release-0.13/manifests/prometheusOperator-service.yaml
  - https://github.com/prometheus-operator/kube-prometheus/blob/release-0.13/manifests/prometheusOperator-serviceAccount.yaml
  - https://github.com/prometheus-operator/kube-prometheus/blob/release-0.13/manifests/prometheusOperator-serviceMonitor.yaml


  # CRDS
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml

namespace: monitoring
