apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: argocd
spec:
  secretName: kopi-quest-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*.kopi.quest'