apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - env:
        - name: PROXY_IMAGE
          value: zyclonite/tailscale:1.42.0
        image: tailscale/k8s-operator:unstable
        name: operator