auth:
  database: vaultwarden
  username: vaultwarden
  existingSecret: vaultwarden-postgresql

primary:
  persistence:
    existingClaim: vaultwarden
  resources:
    requests:
      memory: 500Mi
  livenessProbe:
    enabled: false

volumePermissions:
  enabled: true