auth:
  database: vaultwarden
  username: vaultwarden
  existingSecret: vaultwarden-postgresql

primary:
  persistence:
    existingClaim: vaultwarden
  resources:
    requests:
      memory: 500Mi
  # podSecurityContext:
  #   fsGroup: 1000
  #   runAsUser: 1000

volumePermissions:
  enabled: true