apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: grafana
  repo: https://grafana.github.io/helm-charts
  version: 7.0.17
  releaseName: grafana
  namespace: grafana
  valuesFile: values.yaml

namespace: grafana
