apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
data:
  default-setting.yaml: |-
    create-default-disk-labeled-nodes: true
    default-replica-count: 1