apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: tuya-smartplug-exporter
  repo: https://rkosegi.github.io/helm-charts
  version: v1.0.3
  releaseName: tuya-smartplug-exporter
  namespace: monitoring
  valuesFile: values.yaml

resources:
  - resources/tuya-config.yaml

patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
      name: tuya-smartplug-exporter
