apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 25.8.2
  releaseName: prometheus
  namespace: prometheus
  valuesFile: values.yaml

namespace: prometheus
