prometheus-pushgateway:
  enabled: false
alertmanager:
  enabled: false

server:
  ingress:
    enabled: true
    hosts:
      - prometheus.kopi.quest
  persistentVolume:
     enabled: true
     storageClass: longhorn-sd
     size: 4Gi
