apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
  name: transmission
spec:
  ports:
  - name: main
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
  type: ClusterIP