apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml
  - resources
  - nodes

patches:
  - path: patches/longhorn-default-setting.yaml

namespace: longhorn-system
