apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: espresso-1
  namespace: longhorn-system
spec:
  disks:
    espresso-1-storage:
      allowScheduling: true
      evictionRequested: false
      path: /mnt/extstorage
      storageReserved: 0
      tags: []
      diskType: filesystem
