apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: espresso-2
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    espresso-2-storage:
      allowScheduling: true
      evictionRequested: false
      path: /mnt/extstorage
      storageReserved: 0
      tags: []
      diskType: filesystem
