apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: espresso-1
  namespace: longhorn-system
  labels:
    node.longhorn.io/create-default-disk: true
spec:
  allowScheduling: true
  disks:
    local-storage:
      allowScheduling: true
      evictionRequested: false
      path: /var/lib/longhorn
      tags:
      - sd
      diskType: filesystem
