{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tuya-config",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tuya-config",
        "namespace": "monitoring",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "config.yaml": "AgBt3qIiN/601mWuBJtTdKqBZMYoE+93IjvdlcwY+zXn+XyKcsrXw8nPYYJL6etukOvgvEQZfm+NNHNvn2e92Mh1ks7IL+xAZY2FV4jqOMZ9vA1PA/lhwLqyoOfkbkg2INrKWlc0FVlcIAbO5ZP0YwnICmdExSAovFQ1FMoCM0c8lvBxsbTGuXqI+b9CGo0fuOqECHhb2UnARL/6rWmd1w3TO7eWzEcAZdD/NwYuZjZfwBpY/gmS4xzvdhROmxAIbQLDg2/6ZHfgVQl3R/51/6a/xD3nOkVdH2uMrN4Vxo8BOPqmkn71NyggIf+EaTfF+K2i8el5sciwJKROlMSRN4ARDdQiXAuiLFT0nsDkRiBLBcHDN8Xo4baOcKnQ1UJEDt+ezYG/F9FLo1chzo1lptEhK8dyOU0fc9PLhqpDuYrl+ul53BHYNzt8R8L6/8pAbI6oI3zfi8v9TYUzpbJTBFlci1EEiLtgkD0N+7j6Xg7FBMhaAuOnuTF8kD0dovgvEZ/AZqJs8eV2JHH/el+U/Ykhg80V7XkBac5Bnw5B9KcM4lUTDLOuXnc5oiTxxglOZpBNvUQpwd+2BKACdwwvgF8veJd84aymDkm+qx26zqeDD9L0hqQqnx5ivgyksJECfnQglKFyHp1FBA02UitbLqLeS0Nmqm/DMDepv8SS4mNDSJ2CzngIiGnLPE/g/RUDpKkk/WshIhEzKhqLT3UQi/8eF4pQP8jIEMVKKccm3OGOzyGtASJZA4DpUe7GQ7Ol6IdweLMM77PNb7mleOuLPFc6/7oVQR0biVGfGtrACZ7lNngMqJ3mPB8ydUw="
    }
  }
}
