apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: prowlarr-config
spec:
  storageClassName: synology-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
