apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: prowlarr
    app.kubernetes.io/name: prowlarr
  name: prowlarr
  namespace: media
spec:
  ports:
  - name: main
    port: 80
    protocol: TCP
    targetPort: 9696
  selector:
    app.kubernetes.io/instance: prowlarr
    app.kubernetes.io/name: prowlarr
  type: ClusterIP