apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gios
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: gios
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/JosephABC/argocd.git
    targetRevision: HEAD
    path: .kustomize/gios
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true