apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingresses
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/josephangbc/argocd.git
    targetRevision: HEAD
    path: .kustomize/ingresses
    plugin:
      name: kustomize-enable-helm
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
      # - CreateNamespace=true