apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeseal
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/josephangbc/argocd.git
    targetRevision: HEAD
    path: .kustomize/kubeseal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true