apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: longhorn-temp
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/JosephABC/argocd.git
    targetRevision: HEAD
    path: .kustomize/longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true