apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/JosephABC/argocd.git
    targetRevision: HEAD
    path: .kustomize/media
    # plugin:
    #   name: kustomize-enable-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true