apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: jellyseerr
    app.kubernetes.io/name: jellyseerr
  name: jellyseerr
  namespace: media
spec:
  ports:
  - name: main
    port: 80
    protocol: TCP
    targetPort: 5055
  selector:
    app.kubernetes.io/instance: jellyseerr
    app.kubernetes.io/name: jellyseerr
  type: ClusterIP