replicaCount: 1

image:
  repository: ghcr.io/linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ  
    value: Asia/Singapore

service:
  type: ClusterIP
  port: 80

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: media-config
  - name: data
    persistentVolumeClaim:
      claimName: media-data

volumeMounts:
  - name: config
    mountPath: /config
    subPath: sonarr
  - name: data
    mountPath: /downloads
    subPath: "downloads/transmission" # Path where sonarr picks up downloaded episodes
  - name: data
    mountPath: /tv
    subPath: library/tv # Path where sonarr moves and renames the episodes

