apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/letsencrypt-issuer-stg.yaml
  - resources/letsencrypt-issuer-prd.yaml
  - resources/cloudflare-apikey-secret.yaml

namespace: cert-manager