apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
  annotations:
    nfs.io/storage-path: vaultwarden
spec:
  storageClassName: synology-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi