apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: authentik 
  repo: https://charts.goauthentik.io
  version: 2023.10.7
  releaseName: authentik 
  namespace: authentik
  valuesFile: values.yaml

