authentik:
  secret_key: $authentik-secretkey:authentik-secretkey
  postgresql:
    host: postgresql
    user: postgres
    password: $postgresql:postgresql-password
  redis:
    host: redis-master
    password: $redis:redis-password

ingress:
  # Specify kubernetes ingress controller class name
  ingressClassName: nginx
  enabled: true
  hosts:
    # Specify external host name
    - host: authentik.kopi.quest
      paths:
        - path: "/"
          pathType: Prefix
