authentik:
  postgresql:
    host: postgresql-0
    password: $postgresql:postgresql-password
  redis:
    host: redis-master-0
    password: $redis:redis-password

ingress:
  # Specify kubernetes ingress controller class name
  ingressClassName: nginx
  enabled: true
  hosts:
    # Specify external host name
    - host: authentik.kopi.quest
      paths:
        - path: "/"
          pathType: Prefix
