global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secretkey
          key: authentik-secretkey
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: password
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis
          key: redis-password
server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - authentik.kopi.quest
    paths:
      - /
    pathType: Prefix
