envValueFrom:
  AUTHENTIK_SECRET_KEY:
    secretKeyRef:
      key: authentik-secretkey
      name: authentik-secretkey
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      key: password
      name: postgresql
  AUTHENTIK_REDIS__PASSWORD:
    secretKeyRef:
      key: redis-password
      name: redis
  
ingress:
  # Specify kubernetes ingress controller class name
  ingressClassName: nginx
  enabled: true
  hosts:
    # Specify external host name
    - host: authentik.kopi.quest
      paths:
        - path: "/"
          pathType: Prefix

authentik:
  log_level: debug