controller:
  service:
    loadBalancerIP: "192.168.18.153"
    annotations:
      tailscale.com/expose: "true"
  extraArgs:
    "default-ssl-certificate": "cert-manager/kopi-quest-tls"

  ingressClassResource:
    name: nginx-vpn-external
    default: false
    controllerValue: k8s.io/nginx-vpn-external
  
  ingressClass: nginx-vpn-external
