apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synology-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-vpn-external
  rules:
  - host: nas.kopi.quest
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synology-service
            port:
              number: 80
