apiVersion: v1
kind: Service
metadata:
  name: synology-service
spec:
  type: ExternalName
  externalName: nas.local
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
