serviceWeb:
  type: LoadBalancer
  loadBalancerIP: "192.168.18.151"

serviceDns:
  mixedService: true
  type: LoadBalancer
  loadBalancerIP: "192.168.18.152"

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - pihole.local

dnsmasq:
  customDnsEntries:
    - address=/pihole.local/192.168.18.150
    - address=/router.local/192.168.18.1
    - address=/kopi.quest/192.168.18.150
