apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/JosephABC/tuya-prometheus-exporter/master/manifests/deploy.yaml
  - resources/tuya-config.yaml

patches:
  - path: patches/servicemonitor.yaml
    target:
      kind: ServiceMonitor
      name: tuya-prometheus-exporter
  - path: patches/delete-secret.yaml