apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-config
  labels:
    type: "local"
spec:
  storageClassName: ""
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/extstorage/media/config"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - espresso-1