apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-config
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"
  volumeName: media-config