apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Gi"