apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-data
spec:
  storageClassName: synology-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
