apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: arr-ingress
  annotations:
    # This should be the in-cluster DNS name for the authentik outpost service
    # as when the external URL is specified here, nginx will overwrite some crucial headers
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    # If you're using domain-level auth, use the authentication URL instead of the application URL
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://authentik.kopi.quest/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/auth-log-format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$host" "$scheme" "$request_uri" "$sent_http_location"'
spec:
  ingressClassName: nginx
  rules:
  - host: prowlarr.kopi.quest
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 9696
  - host: radarr.kopi.quest
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80
