apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: media-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: media.kopi.quest
    http:
      paths:
      - path: "/transmission"
        pathType: Prefix
        backend:
          service:
            name: transmission
            port:
              number: 9091
      - path: "/sonarr"
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 80
      - path: "/prowlarr"
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 9696
      - path: "/radarr"
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: 8096
