apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: media-ingress
  annotations:
      # This should be the in-cluster DNS name for the authentik outpost service
      # as when the external URL is specified here, nginx will overwrite some crucial headers
      nginx.ingress.kubernetes.io/auth-url: |-
          http://authentik.authentik.svc.cluster.local:9443/outpost.goauthentik.io/auth/nginx
      # If you're using domain-level auth, use the authentication URL instead of the application URL
      nginx.ingress.kubernetes.io/auth-signin: |-
          https://authentik.kopi.quest/outpost.goauthentik.io/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
      nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
spec:
  ingressClassName: nginx
  rules:
  - host: media.kopi.quest
    http:
      paths:
      - path: "/transmission"
        pathType: Prefix
        backend:
          service:
            name: transmission
            port:
              number: 9091
      - path: "/sonarr"
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 80
      - path: "/prowlarr"
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 9696
      - path: "/radarr"
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: 8096
