apiVersion: v1
kind: ConfigMap
metadata:
  name: yt-dlp-config
  namespace: media
data:
  yt-dlp.conf: |
    -x
    --audio-format mp3
    --download-archive /archive/download-archive.txt
    -P "/music"
    --embed-metadata
    --write-thumbnail
    -o "%(artist)s - %(album)s - %(title)s.%(ext)s"
  yt-dlp-script.sh: |
    apk add ffmpeg
    yt-dlp --update

    while true
    do
      yt-dlp https://music.youtube.com/playlist?list=PLG-F5zLmWfX5acpw2euWH7N8Ko-g7Y7UR
      sleep 60
    done
