apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: yt-dlp
    app.kubernetes.io/name: yt-dlp
  name: yt-dlp
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: yt-dlp
      app.kubernetes.io/name: yt-dlp
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: yt-dlp
        app.kubernetes.io/name: yt-dlp
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - env:
        - name: TZ
          value: Asia/Singapore
        image: tnk4on/yt-dlp:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        args:
        - /tmp/yt-dlp-script.sh
        name: yt-dlp
        # ports:
        # - containerPort: 5055
        #   name: main
        #   protocol: TCP
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /tmp/yt-dlp-script.sh
          name: yt-dlp-config
          subPath: yt-dlp-script.sh
        - mountPath: /etc/yt-dlp.conf
          name: yt-dlp-config
          subPath: yt-dlp.conf
        - mountPath: /archive
          name: data
          subPath: yt-dlp-config/archive
        - name: data
          mountPath: /music
          subPath: library/music
      volumes:
      - name: yt-dlp-config
        configMap:
          name: yt-dlp-config
          defaultMode: 0777
      - name: data
        persistentVolumeClaim:
          claimName: data
