apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: yt-dlp
    app.kubernetes.io/name: yt-dlp
  name: yt-dlp
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: yt-dlp
      app.kubernetes.io/name: yt-dlp
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: yt-dlp
        app.kubernetes.io/name: yt-dlp
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - env:
        - name: TZ
          value: Asia/Singapore
        image: tnk4on/yt-dlp:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        args:
        - /tmp/yt-dlp-script.sh
        name: yt-dlp
        # ports:
        # - containerPort: 5055
        #   name: main
        #   protocol: TCP
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /tmp/yt-dlp-script.sh
          name: script
          subPath: yt-dlp-script.sh
      #   - mountPath: /app/config
      #     name: config
      #     subPath: jellyseerr
      volumes:
      - name: script
        configMap:
          name: yt-dlp-script
      # - name: config
      #   persistentVolumeClaim:
      #     claimName: media-config
