apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  template:
    spec:
      containers:
      - name: prowlarr
        volumeMounts:
        - mountPath: /dev/shm
          name: media-volume
          subPath: "configs/prowlarr/dev/shm"
          readOnly: false
        - mountPath: /shared
          name: media-volume
          subPath: "configs/prowlarr/shared"
          readOnly: false
        - mountPath: /tmp
          name: media-volume
          subPath: "configs/prowlarr/tmp"
          readOnly: false
        - mountPath: /var/logs
          name: media-volume
          subPath: "configs/prowlarr/var/logs"
          readOnly: false
        - mountPath: /var/run
          name: media-volume
          subPath: "configs/prowlarr/var/run"
          readOnly: false
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: "media-volume" # PersistentVolumeClaim created earlier
