apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  template:
    spec:
      containers:
      - name: prowlarr
        env:
        - name: TZ
          value: UTC
        - name: PUID
          value: 1000
        - name: PGID
          value: 1000
        - name: UMASK
          value: 002
        volumeMounts:
        - name: media-volume
          mountPath: /config
          subPath: configs/prowlarr
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: "media-volume" # PersistentVolumeClaim created earlier
