apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: jellyfin-config-pvc
spec:
  storageClassName: synology-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
