apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: longhorn.kopi.quest
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
