apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-config
  annotations:
    nfs.io/storage-path: config
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"