apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-data-nfs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Gi"