apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 18.0.1
  releaseName: authentik-redis
  namespace: authentik
  valuesFile: values.yaml

